spring.application.name=Spring-Security
spring.security.user.name=Aditya
spring.security.user.password=1234

#Same Site Strict
server.servlet.session.cookie.same-site=strict

# Database - update credentials before running
#Connection Details with Postgres server
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/DB}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update